<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ruanyr-p1" ignored="1" name="D:/localRespority/ConfigurationAnnotations" tests="11" failures="1" timestamp="2022-08-16T10:43:01 CST" time="27.875" errors="0">
  <testcase name="beforeTest" time="0.003" classname="com.yiyibai.DBConfig"/>
  <testcase name="getTest" time="1.385" classname="com.yiyibai.HttpTest"/>
  <testcase name="runOtherTest2" time="0.0" classname="com.yiyibai.TestDBConnection"/>
  <testcase name="httpClientTest" time="21.061" classname="com.yiyibai.TestGetApi"/>
  <testcase name="test1" time="0.0" classname="com.yiyibai.TestDataProvider3"/>
  <testcase name="test1" time="0.001" classname="com.yiyibai.TestDataProvider3"/>
  <testcase name="test2" time="0.001" classname="com.yiyibai.TestDataProvider3"/>
  <testcase name="test2" time="0.0" classname="com.yiyibai.TestDataProvider3"/>
  <testcase name="divisionWithException" time="0.001" classname="com.yiyibai.TestRuntime"/>
  <testcase name="testThisShouldPass" time="4.015" classname="com.yiyibai.TimeoutTest"/>
  <testcase name="testThisShouldFail" time="1.005" classname="com.yiyibai.TimeoutTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.yiyibai.TimeoutTest.testThisShouldFail() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.yiyibai.TimeoutTest.testThisShouldFail() didn't finish within the time-out 1000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.TestNG.privateMain(TestNG.java:1371)
at org.testng.TestNG.main(TestNG.java:1335)
]]>
    </failure>
  </testcase> <!-- testThisShouldFail -->
  <testcase name="runOtherTest1" time="0.0" classname="com.yiyibai.TestDBConnection">
    <ignored/>
  </testcase> <!-- runOtherTest1 -->
</testsuite> <!-- D:/localRespority/ConfigurationAnnotations -->
